/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StudySession {
  'id' : string,
  'userId' : Principal,
  'durationMinutes' : bigint,
  'subjectId' : string,
  'notes' : string,
  'timestamp' : Time,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubject' : ActorMethod<[string, string, string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTotalStudyTimePerSubject' : ActorMethod<
    [Principal],
    Array<[string, bigint]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStudySessions' : ActorMethod<[Principal], Array<StudySession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logStudySession' : ActorMethod<[string, bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];